[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#275df5"
backgroundColor = "#f6f8fc"
secondaryBackgroundColor = "#e9eefb"
textColor = "#14213d"
font = "sans serif"
